### ISSUE TITLE
여긴 뭐죠?

### ISSUE THREAD

**Issue by dohyub** [dailystudygroup/daily-learn#1]
홍승우씨?

**Comment by dohyub** [comment]
자신의 지식을 이 레퍼지에다  공유하실건지?

**Comment by seungwoohong** [comment]
아니요 저희가 공부 하면서 공용으로 생성 되야하는 프로젝트나 
지식 파일 등을 여기서 공유하고자 만든 Organizations 입니다

**Comment by seungwoohong** [comment]
카카오톡에 따로 포스팅하지 않고 여기에 계속 계속 올릴게요 심심하실때마다 보세요 그리고
저희 세미나나 스터디 한 자료도 여기다가 공유 할게요

**Comment by dohyub** [comment]
잘 정리해서 올리세요 내가 보기 편하게
